### ISSUE TITLE
这推送插件要怎么配置

### ISSUE THREAD

**Issue by muzailee** [Night-stars-1/sra_plugins_notify#1]
![image](https://github.com/Night-stars-1/sra_plugins_notify/assets/77168105/f3254b1b-25da-4a8f-ae35-6f5152e18d27)
![image](https://github.com/Night-stars-1/sra_plugins_notify/assets/77168105/74b9316f-9c06-4ab4-b93a-4601f79b8a4a)
这两种写法都运行不了插件，直接报错
![image](https://github.com/Night-stars-1/sra_plugins_notify/assets/77168105/2ea8613b-ed13-439d-8b0b-2edd0ec9fe7a)

**Comment by Night-stars-1** [comment]
你应该学习json的基本语法
参考readme的完整配置

**Comment by muzailee** [comment]
> 你应该学习json的基本语法 参考readme的完整配置

我的锅，第二种写法是对的，忘了加逗号了，谢谢
