### ISSUE TITLE
main-beta分支更新资源后无法检测插件

### ISSUE THREAD

**Issue by gongfuture** [Night-stars-1/sra_plugins_notify#2]
如题，签出main-beta分支后只要一更新资源，就会导致插件失效，是否因为更新资源来自main分支？

**Comment by Night-stars-1** [comment]
是的，更新的资源来自main分支

**Comment by gongfuture** [comment]
插件正常使用是否需要不更新，还是说只要不更新脚本那一项就行？

**Comment by Night-stars-1** [comment]
> 插件正常使用是否需要不更新，还是说只要不更新脚本那一项就行？

是的，你可以等beta功能上线正式版
